### ISSUE TITLE
Sample Script/Dataset for BertForTokenClassification

### ISSUE THREAD

**Issue by amirveyseh** [yifding/hetseq#6]
Is there any sample script or dataset for using BertForTokenClassification task?

**Comment by yifding** [comment]
hetseq basically provides a distributed trainer for deep learning projects, BertForTokenClassification is not provided in hetseq.
For BertForTokenClassifcation, please checkout huggingface/transformers code on https://github.com/huggingface/transformers/tree/master/examples/token-classification. They use CONLL2003 dataset provided at https://github.com/huggingface/datasets/blob/master/datasets/conll2003/conll2003.py.
